### ISSUE TITLE
How to disable the bookmarks bar in new tab?

### ISSUE THREAD

**Issue by FloraMaeWolfe** [maxmilton/new-tab#2142]
I have no use for the bookmarks bar in the new tab page because I have the bookmarks bar always shown. I would like to remove that bit of clutter but it seems there is no way to disable this feature in the extension?

Thank you.

**Comment by maxmilton** [comment]
That sounds like a reasonable request.

I done some testing and there was no performance impact adding this feature, so I've added it in <https://github.com/maxmilton/new-tab/commit/896bc18d8750255a61f83382b7430da5b96eea6d>. The extension's settings page is in dire need of a revamp, but other than that, it works as expect.

You can get it now if you're willing the build the `next` branch for yourself. Otherwise I'll close this issue once a new version is published on the chrome web store.

**Comment by maxmilton** [comment]
Closing now as the change was merged and released in <https://github.com/maxmilton/new-tab/releases/tag/v0.23.0>. It's been submitted to the [Chrome Webstore](https://chrome.google.com/webstore/detail/new-tab/cpcibnbdmpmcmnkhoiilpnlaepkepknb) and once approved it will roll out to users.
