### ISSUE TITLE
Browser Data Sync And Backup

### ISSUE THREAD

**Issue by sheldonhull** [maxmilton/new-tab#2192]
If I missed an open issue or project item please let me know.
I saw mentioned that this was desired for the future, and want to follow for updates if this is planned.

Thanks for building this!

**Comment by maxmilton** [comment]
Love the idea!

The settings page definitely needs a refresh. Since this project started as something I built mainly for myself, some features are still a bit undercooked. I’m keen to refactor it to make everything easier to use and understand, while still keeping (or even boosting) performance.

I tried syncing settings by default in the past but found it annoying because I like to keep different settings per browser. However, if sync was not automatic but something that users need to manually trigger then it sounds great :slightly_smiling_face:

**Comment by sheldonhull** [comment]
I've seen some extensions that opted to just require a checkbox to enable and then it was good from there. 
I do recall chrome local storage has some fixed limits so opting to allow google drive or something else for app storage might be an option too. If I get a chance I'll do a little digging as well. 

Regarding another browsers, I think that's why Toby has the tag concept. I tag groups for work and for home and just pick the ones I want to see for the environment.

**Comment by sheldonhull** [comment]
Used copilot workspace so can experiment next week to see if this gave a good start. YMMV so I put as draft. I'm new to chrome extensions so figured it would get a better start than me.

**Comment by maxmilton** [comment]
Added as an experimental feature in #2208.

Implemented in a way where there's zero runtime overhead. Settings sync is optional and opt-in. It can be set to automatically sync on browser profile load or manually in the settings UI. The Settings UI still needs work but that's for another time.

**Comment by maxmilton** [comment]
It's available for manual install in a pre-release: https://github.com/maxmilton/new-tab/releases/tag/v0.24.0-next.0
