### ISSUE TITLE
Black flashing when using white theme

### ISSUE THREAD

**Issue by mammuth** [maxmilton/new-tab#260]
When using the extension with the white theme, the screen is flashing black shortly when loading the new tab page.

Maybe CSS for the black theme is applied on load and the white theme CSS is overwriting it later on?

**Comment by MaxMilton** [comment]
> Maybe CSS for the black theme is applied on load and the white theme CSS is overwriting it later on?

Actually, that's exactly what's happening! All the CSS is already embedded into the page but the dark theme is loaded by default. Once the JS loads we wait for `chrome.storage.sync.get` to get the users theme setting and apply a class to the body. That's why there's a flash of the dark theme.

I tried other techniques for loading the theme styles but this has been the fastest so far while still allowing the user to choose a theme. I'm keen to hear any suggestions about this though :smiley: 

The logic is in [src/loader.js](https://github.com/MaxMilton/new-tab/blob/master/src/loader.js) if you're curious.

On lower powered machines or when there's a lot of open tabs etc. I've found the flash is more frequent. I have some ideas about how to reduce this but I'm not sure it can be eliminated altogether.

**Comment by mammuth** [comment]
Thanks for the information! 
Makes total sense and I'm not quite sure how to improve it.

You could argue that applying the bright theme by default is better because the usual browser background (eg. current webpage) is probably rather bright than dark and as a result the flash when loading the dark theme later on wouldn't be that "heavy". But I'm not sure whether that really makes sense 😊 
On the other side: You're probably assuming that more people use the black theme, which is why loading that by default is preferable?

> On lower powered machines or when there's a lot of open tabs etc. I've found the flash is more frequent.
Yep, you're right. I'm not always experiencing it, just sometimes.

**Comment by maxmilton** [comment]
It's been a while but even with the latest changes in the `next` branch, there hasn't been much improvement in theme loading speed. Although I did change settings storage from `chrome.storage.sync` to `chrome.storage.local` which saw a small performance improvement (which means settings will _not_ be synchronised to a user's Google account).

There have been many performance improvements to speed up the initial page launch so hopefully flashes are less prominent. But due to the nature of the delay between loading the page before asynchronously getting the user theme setting and applying a class to the document body, it's probably going to remain an issue.

I did consider using a background script to handle settings data but messaging between the new tab page and the background script also has a delay which can result in a flash. Keeping even a blank persistent background script open does have the benefit of forcing Chrome to keep the extension's assets in memory (faster new tab open) but has the downside of chewing up memory so I decided against it.

About which theme should be the default, my thinking here is dark theme should remain the default. If you get a flash of dark before loading a light theme it's not a big deal. However, if it's the middle of the night and you get a flash of white before loading a dark theme it can be blinding! I have some ideas for better theme customisation in future but it's likely the default page colour will be dark to prevent blinding users :sun_with_face: 

Going to close the issue for now but might revisit this in future!

**Comment by maxmilton** [comment]
So... after thinking more about the issue I was able to properly fix it!

For whatever reason I was stuck thinking I had to use the async `chrome.storage` API, but as it turns out using good old `localStorage` was the answer. Because `localStorage` is sync it blocks the page from rendering until it's done, so no more flash of default theme colour!

Since the background script idea was also on my mind, it's been added as an experiment so it can be used in more scenarios before making a decision whether to keep it or not. In my local testing memory consumption never went over about 80 Mb (after the browser's garbage collection has run) so maybe it's acceptable in return for the perceived performance boost.

Both these changes are available in <https://github.com/maxmilton/new-tab/releases/tag/v0.16.3>.
