### ISSUE TITLE
Top sites more important than open tabs

### ISSUE THREAD

**Issue by stalkerg** [maxmilton/new-tab#271]
Will be good to configure the order of elements on the page. 
I have information about all tabs in tabs anyway. :)

**Comment by MaxMilton** [comment]
It's a good point that different users will value each results list differently. Personally I prefer tabs at the top but I've asked around and some people also prefer top sites first.

I'll have a go at making this a setting, perhaps a drag and drop UI for the 4 different results lists. It will be a challenge making this work with the kind of speed I want from the page load because getting the user settings from storage is async and effects the code execution order... but it's something I need to address for loading the theme too.

**Comment by maxmilton** [comment]
In the setting UI it's now possible to reorder or even remove sections entirely. It's been a thing for a while even in the current public Chrome Web Store version so I'm closing this issue.

To be honest the setting UI need visual improvement but it does work. I've listed this as a blocker task in preparation for the next public release in <https://github.com/maxmilton/new-tab/issues/1118>.
