### ISSUE TITLE
Bookmarks Overflow

### ISSUE THREAD

**Issue by DanielSokil** [MaxMilton/new-tab#92]
I have tons of bookmarks, Unable to access all of them.
![screenshot from 2018-06-01 04-11-39](https://user-images.githubusercontent.com/24403355/40829628-0345703c-6552-11e8-8b25-8aead96c3368.png)

**Comment by MaxMilton** [comment]
This has been fixed in release `v0.12.0` and  `v0.12.1`. Overflowing bookmarks will now be placed into a "»" folder just like in the browser's normal bookmarks bar 🎉

The way I've implemented it is fine, however, there's definitely room for some performance improvements. Once I have some free time, that's what I'll focus on.

Closing this for now but please let me know if you run into any issues.

**Comment by DanielSokil** [comment]
### I'm still having issues with this, Not all bookmarks show up. I think if you allowed overflow, so a user can scroll down, should solve this issue.
![screenshot from 2018-08-28 11-52-33](https://user-images.githubusercontent.com/24403355/44734900-01c29080-aab9-11e8-930b-a34eacd068d4.png)
![screenshot from 2018-08-28 11-52-46](https://user-images.githubusercontent.com/24403355/44734904-05561780-aab9-11e8-8bad-3014ddfc7e31.png)

**Comment by DanielSokil** [comment]
Maybe with a custom performant scroll bar: https://github.com/Diokuz/baron (;
Default does not match `new-tab` theme.

**Comment by DanielSokil** [comment]
Also, is there some kind of delay when hovering over `»`? it's not as responsive as the menu bar on the left.

**Comment by MaxMilton** [comment]
This has been addressed in the `next` branch, although it still needs more work before it's stable enough for release.

**Comment by s0kil** [comment]
Will give it a go.
